fpath=(/Users/jiajunw/homebrew/share/zsh-completions $fpath)

export LANG="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"

alias ls='ls --color=auto -h'

# {{{ homebrew
export HOMEBREW_PREFIX="/opt/homebrew";
export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
export HOMEBREW_REPOSITORY="/opt/homebrew";
export HOMEBREW_NO_ANALYTICS=1
export HOMEBREW_NO_AUTO_UPDATE=1

prepend_path $HOMEBREW_ROOT/bin
# }}}

# {{{ Android
export ANDROID_ROOT=$HOME/prefix/opt/android-sdk
append_path $ANDROID_ROOT/platform-tools:$ANDROID_ROOT/tools
# }}}

# {{{ VSCode
append_path "/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
# }}}

# {{{ NVM
export NVM_DIR="$HOME/.nvm"
include $NVM_DIR/nvm.sh
include $NVM_DIR/bash_completion
# }}}

# vim: set foldmethod=marker filetype=zsh :
